### ISSUE TITLE
[Django] Problem installing fixture 'initial_data.json'

### ISSUE THREAD

**Issue by gourneau** [obfuscurity/synthesize#28]
Installed using 69a9b95be834268e21dffa1d04fd4a3275c691f7 on a fresh Ubuntu 14.04.2 LTS VM

Everything seems to work, but I got this minor error during install.

```
<snip>
+ cd /opt/graphite/webapp/graphite
+ cp /home/synthego/synthesize/templates/graphite/webapp/initial_data.json /home/synthego/synthesize/templates/graphite/webapp/initial_data.json.0_9_x /home/synthego/synthesize/templates/graphite/webapp/local_settings.py .
+ [[ 0.9.13-pre1 == \0\.\9\.\x ]]
++ cut -d ' ' -f 1
++ md5sum
++ date
+ sed -i -e s/UNSAFE_DEFAULT/48922294026c32d3247a15a79c1ec3c6/ local_settings.py
+ python manage.py syncdb --noinput
Creating tables ...
Creating table account_profile
Creating table account_variable
Creating table account_view
Creating table account_window
Creating table account_mygraph
Creating table dashboard_dashboard_owners
Creating table dashboard_dashboard
Creating table events_event
Creating table url_shortener_link
Creating table auth_permission
Creating table auth_group_permissions
Creating table auth_group
Creating table auth_user_user_permissions
Creating table auth_user_groups
Creating table auth_user
Creating table django_session
Creating table django_admin_log
Creating table django_content_type
Creating table tagging_tag
Creating table tagging_taggeditem
Installing custom SQL ...
Installing indexes ...
Problem installing fixture 'initial_data.json': Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/loaddata.py", line 196, in handle
    obj.save(using=using)
  File "/usr/local/lib/python2.7/dist-packages/django/core/serializers/base.py", line 165, in save
    models.Model.save_base(self.object, using=using, raw=True)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 529, in save_base
    rows = manager.using(using).filter(pk=pk_val)._update(values)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 557, in _update
    return query.get_compiler(self.db).execute_sql(None)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 986, in execute_sql
    cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 818, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/sqlite3/base.py", line 337, in execute
    return Database.Cursor.execute(self, query, params)
IntegrityError: Could not load contenttypes.ContentType(pk=9): UNIQUE constraint failed: django_content_type.app_label, django_content_type.model

</snip>
```

The full log is here https://gist.github.com/gourneau/12b2813cbb00a673f837

**Comment by gourneau** [comment]
Actually this is a bigger issue than I originally thought, because it prevents the admin account from being able to login. 

I just deleted my graphite.db file at `/opt/graphite/storage/graphite.db` and ran `python manage.py syncdb` inside of the `/opt/graphite/webapp/graphite` dir

**Comment by Kosta-Github** [comment]
Is there a fix available for this I could try? I am also running into this issue:
```
IntegrityError: Could not load contenttypes.ContentType(pk=13):
    UNIQUE constraint failed: django_content_type.app_label, django_content_type.model
```

**Comment by obfuscurity** [comment]
I'll take a look at this today. :cake:

**Comment by ZelphirKaltstahl** [comment]
What was the solution here?
