### ISSUE TITLE
possible issue with latest release

### ISSUE THREAD

**Issue by gorsuch** [obfuscurity/synthesize#33]
I just did a fresh synthesize install on Digital Ocean and got the following when attempting to render any graph:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 101, in get_response
    request.path_info)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 300, in resolve
    sub_match = pattern.resolve(new_path)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 300, in resolve
    sub_match = pattern.resolve(new_path)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 209, in resolve
    return ResolverMatch(self.callback, args, kwargs, self.name)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 216, in callback
    self._callback = get_callable(self._callback_str)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 27, in wrapper
    result = func(*args)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 92, in get_callable
    lookup_view = getattr(import_module(mod_name), func_name)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/opt/graphite/webapp/graphite/render/views.py", line 37, in <module>
    from graphite.render.evaluator import evaluateTarget, extractPathExpressions
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 69, in <module>
    from graphite.render.functions import SeriesFunctions
  File "/opt/graphite/webapp/graphite/render/functions.py", line 34, in <module>
    from graphite.render.glyph import format_units
  File "/opt/graphite/webapp/graphite/render/glyph.py", line 20, in <module>
    import cairocffi as cairo
  File "/usr/local/lib/python2.7/dist-packages/cairocffi/__init__.py", line 16, in <module>
    from . import constants
ImportError: cannot import name constants
```

I'll do some more poking about when I have some free time later, but wanted to note this in case anyone else ran across it.

**Comment by obfuscurity** [comment]
I'll take a look when I get home.

Jason Dixon

**Comment by obfuscurity** [comment]
Was this using the DO button or a manual install on the droplet?

Jason Dixon

**Comment by gorsuch** [comment]
It was the DO button, sorry for not mentioning that.

**Comment by obfuscurity** [comment]
I just ran a new install from DO button and it works fine here. It looks like possibly some sort of build error with cairocffi.

**Comment by gorsuch** [comment]
OK, great.  I'll close this out and if I run into it again, I'll try and suss out more detail.  Thanks!
