### ISSUE TITLE
carbon-cache start failure: TypeError: unhashable type: 'MethodicalState'

### ISSUE THREAD

**Issue by il-davidlurth** [obfuscurity/synthesize#64]
I just tried to install and carbon-cache fails to start with this error:

+ service carbon-cache start
Starting carbon-cache-1: Traceback (most recent call last):
  File "/opt/graphite/bin/carbon-cache.py", line 32, in <module>
    run_twistd_plugin(__file__)
  File "/opt/graphite/lib/carbon/util.py", line 96, in run_twistd_plugin
    runApp(config)
  File "/usr/local/lib/python2.7/dist-packages/twisted/scripts/twistd.py", line 25, in runApp
    _SomeApplicationRunner(config).run()
  File "/usr/local/lib/python2.7/dist-packages/twisted/application/app.py", line 380, in run
    self.application = self.createOrGetApplication()
  File "/usr/local/lib/python2.7/dist-packages/twisted/application/app.py", line 440, in createOrGet                  Application
    ser = plg.makeService(self.config.subOptions)
  File "/opt/graphite/lib/twisted/plugins/carbon_cache_plugin.py", line 20, in makeService
    from carbon import service
  File "/opt/graphite/lib/carbon/service.py", line 18, in <module>
    from twisted.application.internet import TCPServer, TCPClient
  File "/usr/local/lib/python2.7/dist-packages/twisted/application/internet.py", line 542, in <modul                  e>
    class _ClientMachine(object):
  File "/usr/local/lib/python2.7/dist-packages/twisted/application/internet.py", line 842, in _Clien                  tMachine
    outputs=[_connect])
  File "/usr/local/lib/python2.7/dist-packages/automat/_methodical.py", line 62, in upon
    self.machine._oneTransition(self, input, enter, outputs, collector)
  File "/usr/local/lib/python2.7/dist-packages/automat/_methodical.py", line 255, in _oneTransition
    tuple(outputTokens))
  File "/usr/local/lib/python2.7/dist-packages/automat/_core.py", line 74, in addTransition
    (inState, inputSymbol, outState, tuple(outputSymbols))
TypeError: unhashable type: 'MethodicalState'
failed
carbon-cache-1 not running

**Comment by obfuscurity** [comment]
Apologies for letting this issue go untouched for so long. I doubt this is still a valid issue but if it is, please try the latest release and report back.

https://github.com/obfuscurity/synthesize/releases/tag/v4.0.0
