### ISSUE TITLE
Synthesize manual install fails - cairocffi does not support Python 2.x anymore

### ISSUE THREAD

**Issue by stuieordie** [obfuscurity/synthesize#76]
Trying to run install script, getting an error about cairocffi not supporting python2

OS Version
```
# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.6 LTS
Release:	14.04
Codename:	trusty
```

```
Downloading/unpacking cairocffi (from -r requirements.txt (line 48))
  Downloading cairocffi-1.0.2.tar.gz (68kB): 68kB downloaded
  Running setup.py (path:/tmp/pip_build_root/cairocffi/setup.py) egg_info for package cairocffi
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_root/cairocffi/setup.py", line 7, in <module>
        'cairocffi does not support Python 2.x anymore. '
    RuntimeError: cairocffi does not support Python 2.x anymore. Please use Python 3 or install an older version of cairocffi.
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_root/cairocffi/setup.py", line 7, in <module>

    'cairocffi does not support Python 2.x anymore. '

RuntimeError: cairocffi does not support Python 2.x anymore. Please use Python 3 or install an older version of cairocffi.

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/cairocffi
Storing debug log for failure in /root/.pip/pip.log
```

**Comment by stuieordie** [comment]
Just noticed this is duplicate of Installation fails (using vagrant) #75
